### PR TITLE
Update postcss-url which supports AlphaImageLoader

### PR DESCRIPTION
**Pull request by isqua**

### CODE REVIEW

**Comment by isqua** [comment]
https://github.com/postcss/postcss-url/pull/55

**Comment by isqua** [comment]
ping

**Comment by isqua** [comment]
ping

**Comment by blond** [comment]
[LGTM](http://lgtm.in/i/Df42)

**Comment by blond** [comment]
Thank you for your contribution!

Fixed in `v1.0.3`.

**Pull request merged**
